#!/bin/sh
# ...


BASE_DN=""
GROUPS_DN=""
USERS_DN=""
LDIF_FILE=""
GROUPS_BLOCKED="::"
USERS_BLOCKED="::"
S4_BASE_DN=""
S4_USER_DN=""
S4_MKPASSWD="samba4u-mkpasswd"

# search for configuration file
CFG_FILE="samba4u.cfg"

[ -r "$CFG_FILE" ] || exit 100
. "./$CFG_FILE"


GROUPS_LOG="$(tempfile)"
USERS_LOG="$(tempfile)"
for f in $GROUPS_LOG $USERS_LOG; do
	:> $f
done

gid_get_name(){
	gid_number="$1"
	gid_get_attr "$gid_number" "name"
}
gid_get_groupid(){
	gid_number="$1"
	gid_get_attr "$gid_number" "objectSid"| sed -e "s%^.*-%%"
}

gid_get_attr(){
	gid_number="$1"
	attr_name="$2"
	ldbsearch -H "/var/lib/samba/private/sam.ldb" --controls "search_options:0:1" -b $S4_BASE_DN "(&(gidNumber=$gid_number)(objectClass=posixGroup))" | sed -ne "/^$attr_name:/s%^.*: %%p"
}

group_list(){
	sed -ne "/^dn:.*,$GROUPS_DN$/{s%^.*cn=%%;s%,.*%%;p}" $LDIF_FILE
}

group_get_attr(){
	group_name="$1"
	attr_name="$2"
	sed -ne "/^dn: cn=$group_name,$GROUPS_DN$/,/^dn:/p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.*: %%;p}"
}
group_get_gid(){
	group_name="$1"
	group_get_attr "$group_name" gidNumber
}
group_get_members(){
	group_name="$1"
	group_get_attr "$group_name" memberUid
}

s4group_add(){
	group_name="$1"
	rc=0
	samba-tool group add "$group_name" 2>/dev/null || rc=$?
	if [ $rc -ne 255 ] && [ $rc -ne 0 ]; then
		return 1
	fi
	rc=0
	if ! ldbsearch -H "/var/lib/samba/private/sam.ldb" --controls "search_options:0:1" -b $S4_BASE_DN "cn=$group_name" gidNumber | grep -q "^gidNumber:" ; then
		gid="$(group_get_gid "$group_name")"
		group_dn="$(ldbsearch -H "/var/lib/samba/private/sam.ldb" -b $S4_BASE_DN "(&(cn=$group_name)(objectclass=group))" dn |sed -ne "/^dn:/s%^dn: %%p")"
		tmpfile="$(tempfile)"
		cat << EOF > $tmpfile
dn: $group_dn
changetype: modify
add:objectclass
objectclass: posixGroup
-
add:gidnumber
gidnumber: ${gid}
EOF
		ldbmodify --url=/var/lib/samba/private/sam.ldb $tmpfile >/dev/null || rc=$?
		rm -f "$tmpfile"
	fi
	return $rc
}

#user's functions

user_list (){
#	sed -ne "/^dn:.*,$USERS_DN$/{s%^.*uid=%%;s%,.*%%;p}" $LDIF_FILE
	sed -ne "/^dn: .*,$USERS_DN$/,/^uid:/p" $LDIF_FILE | sed -ne "/^uid: /s%^.* %%p"
}
user_get_attr(){
	user_name="$1"
	attr_name="$2"
	user_dn="$(sed -ne "1,/^uid: $user_name/p" $LDIF_FILE |grep "^dn: " |tail -1)"
	#sed -ne "/^dn: uid=$user_name,$USERS_DN$/,/^dn:/p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.* %%;p}"
	sed -ne "/^$user_dn$/,/^dn: /p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.*: %%;p}"
	
}


s4user_add (){
	user_name="$1"
	given_name="$(user_get_attr "$user_name" "givenName")"
	sn="$(user_get_attr "$user_name" "sn")"
	gecos="$given_name  $sn"
	mail_address="$(user_get_attr "$user_name" "mail")"
	home_drive="$(user_get_attr "$user_name" "sambaHomeDrive")"
	uidNumber="$(user_get_attr "$user_name" "uidNumber")"
	gidNumber="$(user_get_attr "$user_name" "gidNumber")"
	homeDirectory="$(user_get_attr "$user_name" "homeDirectory")"
	employeeNumber="$(user_get_attr "$user_name" "employeeNumber")"
	# establecer primarygroup
	#groupid="$(gid_get_groupid $gidNumber)"
	MAIL_OPTION=""
	if [ "$mail_address" ] ; then
		MAIL_OPTION="--mail-address=$mail_address"
	fi
	rc=0
	#samba-tool user add "$user_name" --random-password --given-name="$given_name" $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
	#samba-tool user add "$user_name" --random-password $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
	samba-tool user add "$user_name" --use-username-as-cn --random-password $MAIL_OPTION --home-drive="$home_drive" --home-directory="\\estaminas\$user_name" --given-name="$given_name" --surname="$sn" --unix-home="$homeDirectory" --login-shell="/bin/bash" --uid-number="$uidNumber" --gid-number="$gidNumber" --gecos="$gecos" 2> /dev/null || rc=$?
	tmpfile="$(tempfile)"
	if [ $rc -eq 0 ] ; then
		if [ "$employeeNumber" ] ; then
			cat << EOF > $tmpfile
dn: cn=$user_name,$S4_USER_DN
changetype: modify
-
add:employeeNumber
employeeNumber: $employeeNumber
EOF
			ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile >/dev/null || rc=2
			rm -f "$tmpfile"
		fi
		
	elif [ $rc -ne 255 ] ; then
		return 1
	fi
	rc=0

	samba-tool user setexpiry "$user_name" --noexpiry || rc=2
	[ $rc -eq 0 ] || return $rc

	# copiamos password del ldap viejo
	ntpasswd="$(user_get_attr "$user_name" "sambaNTPassword")"
	
	cat << EOF > $tmpfile
dn: cn=$user_name,$S4_USER_DN
changetype: modify
replace: unicodePwd
unicodePwd:: $(/home/depinf/samba-reborn/scripts/samba4u-mkpasswd $ntpasswd) 
EOF
	ldbmodify --url=/var/lib/samba/private/sam.ldb --controls=local_oid:1.3.6.1.4.1.7165.4.3.12:0 -b $S4_BASE_DN $tmpfile >/dev/null || rc=3
	rm -f "$tmpfile"
	return $rc
}


s4add_members(){
	group_name="$1"
	users_file="$2"
	rc=0
	tmpfile="$(tempfile)"
	echo -n $USERS_BLOCKED |sed -e "s%^:%%;s%:$%%"|tr ":" "\n" > $tmpfile

	user_list="$(group_get_attr "$group_name" memberUid | grep -vFf $tmpfile | grep -Ff "$users_file" |tr "\n" ","| sed s%,$%%)"
	if [ "$user_list" ] ; then
		samba-tool group addmembers "$group_name" "$user_list" || rc=$?
	else
		rc=1
	fi
		rm -f $tmpfile
	return $rc
}


# main program
# Add groups old ldap groups to s4
group_list | while read g; do
	if ! echo "$GROUPS_BLOCKED" | grep -q ":$g:" ; then
		rc=0
		s4group_add "$g"  || rc=$?
		if [ $rc -eq 0 ] ; then
			echo "Group $g: added"
			echo "$g" >> $GROUPS_LOG
		else
			echo "==> ERROR adding group: $g ($rc)" >&2
		fi
	fi
done

# Add users from old ldap to s4
user_list | while read u; do
	if ! echo "$USERS_BLOCKED" | grep -q ":$u:" ; then
		rc=0
		s4user_add "$u" || rc=$?
		if [ $rc -eq 0 ] ; then
			echo "User $u: added"
			echo "$u" >> $USERS_LOG
		else
			echo "==> ERROR adding user: $u ($rc)" >&2
		fi
	fi
done

# Add group members to s4 
VALID_USERS="$(tempfile)"
wbinfo -u  |sed -e "s%^.*\\\%%" > "$VALID_USERS"

group_list | while read g; do
	if ! echo "$GROUPS_BLOCKED" | grep -q ":$g:" ; then
		rc=0
		s4add_members "$g" "$VALID_USERS" || rc=$?
		case "$rc" in
			1)
				echo "No members for $g"
				;;
			0)
				echo "Members of $g: added"
				;;
			*)
				echo "==> ERROR adding members of group: $g ($rc)" >&2
		esac
	fi
done
rm -f "$VALID_USERS"

# clean
# find users not added in this run and remove them ¿?
# find groups not added in this run and remove them ¿?
