#!/bin/sh
# ...


BASE_DN="dc=centro,dc=com"
GROUPS_DN="ou=grupos,$BASE_DN"
USERS_DN="ou=usuarios,$BASE_DN"
LDIF_FILE="/home/depinf/backup-2016-05-18.ldif"
GROUPS_BLOCKED="::"
USERS_BLOCKED="::"
S4_BASE_DN="dc=samba,dc=xenial"
S4_USER_DN="cn=Users,$S4_BASE_DN"
GROUPS_LOG="$(tempfile)"
USERS_LOG="$(tempfile)"
for f in $GROUPS_LOG $USERS_LOG; do
	:> $f
done

gid_get_name(){
	gid_number="$1"
	gid_get_attr "$gid_number" "name"
}
gid_get_groupid(){
	gid_number="$2"
	gid_get_attr "$gid_number" "objectSid"| sed -e "s%^.*-%%"
}

gid_get_attr(){
	gid_number="$1"
	attr_name="$2"
	ldbsearch -H "/var/lib/samba/private/sam.ldb" --controls "search_options:0:1" -b $S4_BASE_DN "(&(gidNumber=$gid_number)(objectClass=posixGroup))" | sed -ne "/^$attr_name:/s%^.*: %%p"
}

group_list(){
	sed -ne "/^dn:.*,$GROUPS_DN$/{s%^.*cn=%%;s%,.*%%;p}" $LDIF_FILE
}

group_get_attr(){
	group_name="$1"
	attr_name="$2"
	sed -ne "/^dn: cn=$group_name,$GROUPS_DN$/,/^dn:/p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.*: %%;p}"
}
group_get_gid(){
	group_name="$1"
	group_get_attr "$group_name" gidNumber
}
group_get_members(){
	group_name="$1"
	group_get_attr "$group_name" memberUid
}

s4group_add(){
	group_name="$1"
	rc=0
	samba-tool group add "$group_name" 2>/dev/null || rc=$?
	if [ $rc -ne 255 ] && [ $rc -ne 0 ]; then
		return 1
	fi
	rc=0
	if ! ldbsearch -H "/var/lib/samba/private/sam.ldb" --controls "search_options:0:1" -b $S4_BASE_DN "cn=$group_name" gidNumber | grep -q "^gidNumber:" ; then
		gid="$(group_get_gid "$group_name")"
		group_dn="$(ldbsearch -H "/var/lib/samba/private/sam.ldb" -b $S4_BASE_DN "(&(cn=$group_name)(objectclass=group))" dn |sed -ne "/^dn:/s%^dn: %%p")"
		echo "DN>>>>>>>>$group_name<<<<<<<<<<<<<<<<<<"
		tmpfile="$(tempfile)"
		cat << EOF |tee  $tmpfile
dn: $group_dn
changetype: modify
add:objectclass
objectclass: posixGroup
-
add:gidnumber
gidnumber: ${gid}
EOF
		ldbmodify --url=/var/lib/samba/private/sam.ldb $tmpfile || rc=$?
		rm -f "$tmpfile"
	fi
	return $rc
}

#user's functions

user_list (){
#	sed -ne "/^dn:.*,$USERS_DN$/{s%^.*uid=%%;s%,.*%%;p}" $LDIF_FILE
	sed -ne "/^dn: .*,$USERS_DN$/,/^uid:/p" $LDIF_FILE | sed -ne "/^uid: /s%^.* %%p"
}
user_get_attr(){
	user_name="$1"
	attr_name="$2"
	user_dn="$(sed -ne "1,/^uid: $user_name/p" $LDIF_FILE |grep "^dn: " |tail -1)"
	#sed -ne "/^dn: uid=$user_name,$USERS_DN$/,/^dn:/p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.* %%;p}"
	sed -ne "/^$user_dn$/,/^dn: /p" $LDIF_FILE |sed -ne "/^$attr_name:/{s%^.*: %%;p}"
	
}


s4user_add (){
	user_name="$1"
	given_name="$(user_get_attr "$user_name" "givenName")"
	mail_address="$(user_get_attr "$user_name" "mail")"
	home_drive="$(user_get_attr "$user_name" "sambaHomeDrive")"
	MAIL_OPTION=""
	if [ "$mail_address" ] ; then
		MAIL_OPTION="--mail-address=\"$mail_address\""
	fi
	rc=0
	samba-tool user add "$user_name" --random-password --given-name="$given_name" $MAIL_OPTION --home-drive="$home_drive" 2> /dev/null || rc=$?
	if [ $rc -ne 255 ] && [ $rc -ne 0 ]; then
		return 1
	fi
	rc=0
	if ! ldbsearch -H "/var/lib/samba/private/sam.ldb" --controls "search_options:0:1" -b $S4_BASE_DN "cn=$user_name" uidNumber  | grep -q "^uidNumber:" ; then
		uidNumber="$(user_get_attr "$user_name" "uidNumber")"
		gidNumber="$(user_get_attr "$user_name" "gidNumber")"
		homeDirectory="$(user_get_attr "$user_name" "homeDirectory")"
		employeeNumber="$(user_get_attr "$user_name" "employeeNumber")"
		tmpfile="$(tempfile)"
		cat << EOF > $tmpfile
dn: cn=$user_name,$S4_USER_DN
changetype: modify
add:objectclass
objectClass: posixAccount
-
add:objectclass
objectClass: organizationalPerson
-
add:uidnumber
uiddnumber: $uidNumber
-
add:gidnumber
gidnumber: $gidNumber
-
add:unixhomedirectory
unixhomedirectory: $homeDirectory
-
add:loginshell
loginshell: /bin/bash
-
add:employeeNumber
employeeNumber: $employeeNumber
EOF
		ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile || rc=2
		rm -f "$tmpfile"
	fi
	[ $rc -eq 0 ] || return $rc

	# Añade usuario a su grupo principal en Windows 
	group_name="$(gid_get_name "$gidNumber")"
	samba-tool group addmembers "$group_name" $user_name || rc=3
	#########################################
	[ $rc -eq 0 ] || return $rc

	# establecer primarygroup
	groupid="$(gid_get_groupid "$gidNumber")"

	#set the user to the posix group
	cat << EOF > $tmpfile
dn: cn=$user_name,$S4_USER_DN
changetype: modify
replace: primarygroupid
primarygroupid: $groupid
EOF
	ldbmodify --url=/var/lib/samba/private/sam.ldb -b $S4_BASE_DN $tmpfile || rc=4
	rm -f "$tmpfile"
	[ $rc -eq 0 ] || return $rc

	samba-tool user setexpiry "$user_name" --noexpiry || rc=5
	[ $rc -eq 0 ] || return $rc

	# copiamos password del ldap viejo
	ntpasswd="$(user_get_attr "$user_name" "sambaNTPassword")"
	
	cat << EOF > $tmpfile
dn: cn=$user_name,$S4_USER_DN
changetype: modify
replace: unicodePwd
unicodePwd:: $(/home/depinf/samba-reborn/scripts/samba4u-mkpasswd $ntpasswd) 
EOF
	ldbmodify --url=/var/lib/samba/private/sam.ldb --controls=local_oid:1.3.6.1.4.1.7165.4.3.12:0 -b $S4_BASE_DN $tmpfile || rc=6
	rm -f "$tmpfile"
	return $rc
}


s4add_members(){
	group_name="$1"
	rc=0
	tmpfile="$(tempfile)"
	echo $USERS_BLOCKED |sed -e "s%^:%%;s%:$%%"|tr ":" "\n" > $tmpfile

	user_list="$(group_get_attr "$group_name" memberUid | grep -vFf $tmpfile |tr "\n" ","| sed s%,$%%)"
	samba-tool group addmembers "$group_name" "$user_list" || rc=$?
	rm -f $tmpfile
	return $rc
}


# main program
# Add groups old ldap groups to s4
group_list | while read g; do
	if ! echo "$GROUPS_BLOCKED" | grep -q ":$g:" ; then
		rc=0
		s4group_add "$g"  || rc=$?
		if [ $rc -eq 0 ] ; then
			echo "Group $g: added"
			echo "$g" >> $GROUPS_LOG
		else
			echo "==> ERROR adding group: $g ($rc)" >&2
		fi
	fi
done
# Add users from old ldap to s4
user_list | while read u; do
	if ! echo "$USERS_BLOCKED" | grep -q ":$u:" ; then
		if s4user_add "$u" ; then
			echo "User $u: added"
			echo "$u" >> $USERS_LOG
		else
			echo "==> ERROR adding user: $u" >&2
		fi
	fi
done
# Add group members to s4 
group_list | while read g; do
	if ! echo "$GROUPS_BLOCKED" | grep -q ":$g:" ; then
		if s4add_members "$g" ; then
			echo "Members of $g: added"
		else
			echo "==> ERROR adding members of group: $g" >&2
		fi
	fi
done


# clean
# find users not added in this run and remove them ¿?
# find groups not added in this run and remove them ¿?
